version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: go test app/main_test.go
